# Generated by Django 2.2.6 on 2019-10-14 11:57

# Third party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ManyToManyField(to='bugboard.Member'),
        ),
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(to='bugboard.Tag'),
        ),
        migrations.DeleteModel(
            name='Assignee',
        ),
    ]
