# Generated by Django 2.2.6 on 2019-10-15 09:05

# Third party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugboard', '0002_auto_20191014_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
