# Generated by Django 2.2.6 on 2019-10-16 07:55

# Third party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("bugboard", "0003_task_priority")]

    operations = [
        migrations.AddField(
            model_name="task",
            name="admin_link",
            field=models.URLField(max_length=70, null=True),
        )
    ]
