# Generated by Django 2.2.6 on 2019-10-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugboard', '0004_task_admin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
