# Generated by Django 2.2.6 on 2019-10-16 08:53

# Third party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugboard', '0005_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='admin_link',
            field=models.URLField(default='#', max_length=70),
        ),
    ]
