# Generated by Django 2.2.6 on 2019-10-16 13:48

# Third party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugboard', '0010_auto_20191016_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar_url',
            field=models.URLField(default='https://i.imgur.com/1c85UxD.png', max_length=255),
        ),
    ]
