# Generated by Django 3.0b1 on 2019-10-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugboard', '0011_auto_20191016_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to_id',
        ),
    ]
