# Generated by Django 3.0b1 on 2019-10-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugboard', '0012_remove_task_assigned_to_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='admin_link',
            field=models.URLField(default='#', max_length=70, null=True),
        ),
    ]
