# Generated by Django 3.0rc1 on 2020-04-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugboard', '0013_auto_20191022_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status_id',
        ),
    ]
